### ISSUE TITLE
Plugin uses incompatible Qt library (5.15.0) [release]

### ISSUE THREAD

**Issue by OlafHaag** [iyadahmed/blender_pyqt_example_addon#1]
Hi! I just wanted to try you 0.0.1 release for Windows 11 with Blender 3.5 (portable).
Upon acitvating the add-on the message box pops up, but I wasn't able to close it, and the blender main loop was blocked.
The console showed these errors:

```
qt.core.plugin.loader: In C:/Users/olaf/AppData/Local/Temp/_MEI73162/PyQt5/Qt5/plugins/platforms/qminimal.dll:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In C:/Users/olaf/AppData/Local/Temp/_MEI73162/PyQt5/Qt5/plugins/platforms/qoffscreen.dll:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In C:/Users/olaf/AppData/Local/Temp/_MEI73162/PyQt5/Qt5/plugins/platforms/qwebgl.dll:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In C:/Users/olaf/AppData/Local/Temp/_MEI73162/PyQt5/Qt5/plugins/platforms/qwindows.dll:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In C:/Users/olaf/AppData/Local/Temp/_MEI73162/PyQt5/Qt5/plugins/platformthemes/qxdgdesktopportal.dll:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In C:/Users/olaf/AppData/Local/Temp/_MEI73162/PyQt5/Qt5/plugins/styles/qwindowsvistastyle.dll:
  Plugin uses incompatible Qt library (5.15.0) [release]
```

which is curious, since the add-on comes bundled with PyQt6? I use BQT in another portable Blender version.

Trying to remove the add-on after it was activating threw:
`PermissionError: [WinError 5]: 'C:\\Users\\olaf\\AppData\\Roaming\\Blender Foundation\\Blender\\3.5\\scripts\\addons\\blender_pyqt6_example_addon\\extern\\PyQt6\\Qt6\\bin\\Qt6Core.dll'`

Could be removed after I had to force close blender and the add-on wasn't loaded yet.

Looking forward to see how this will come along if you keep working at it!

**Comment by iyadahmed** [comment]
I think this is some sort of conflict with other installed plugins, as for the second error indeed this is a famous issue with Windows, Linux and macOS don't suffer from it, I plan to fix it in future

**Comment by hannesdelbeke** [comment]
it likely clashes with the BQT QApplication that's created on startup. you can't combine 2 different QT bindings AFAIK

**Comment by iyadahmed** [comment]
> > it likely clashes with the BQT QApplication that's created on startup. you can't combine 2 different QT bindings AFAIK
> 
> No. This Blender version that I tested the addon with never used BQT. It's a portable version.

Agree but BQT or something else could be modifying Blender paths or so to load its own Qt plugins

I pushed this commit in hopes to fix the plugins issue can you confirm it works, I can't reproduce the issue here
https://github.com/iyadahmed/blender_pyqt_example_addon/commit/ee47b7562b5bd564082114a636e4d42be461abc8

Here's the release built with commit
https://github.com/iyadahmed/blender_pyqt_example_addon/releases/tag/v0.0.2

**Comment by OlafHaag** [comment]
Thanks for looking into it! Unfortunately that commit didn't fix the issue, but I did some digging and found the cause to be the [Blender Launcher](https://dotbow.github.io/Blender-Launcher/) I use!

First, I loaded factory settings and looked at the debug logs. In the log, Blender paths are all default, as are enabled addons.
Looking into my environment variables from outside Blender, I also don't have any Qt related paths on my PATH environment variable. HOWEVER, when listing PATH from Blender's Python REPL, I see `C:\Users\olaf\AppData\Local\Temp\_MEI397042` which contains the PyQt5 files. There are over 130 of similarly named temp folders with PyQt5 stuff. 
I now suspect the [Blender Launcher](https://dotbow.github.io/Blender-Launcher/) is adding these folders and using PyQt5. Since I start Blender from it, the path is inherited from Blender. That much I confirmed. Starting from the executable directly, not  from the launcher doesn't raise the errors.

Maybe this [issue](https://github.com/pyinstaller/pyinstaller/issues/6297) is related.

FYI: the version in the bl_info didn't get updated to 0.0.2, it still shows 0.0.1.

**Comment by hannesdelbeke** [comment]
can confirm blender launcher uses PyQt5, see code in here https://github.com/DotBow/Blender-Launcher/blob/v1.15.0-stable/source/windows/main_window.py.

**Comment by iyadahmed** [comment]
> Thanks for looking into it! Unfortunately that commit didn't fix the issue, but I did some digging and found the cause to be the [Blender Launcher](https://dotbow.github.io/Blender-Launcher/) I use!
> 
> First, I loaded factory settings and looked at the debug logs. In the log, Blender paths are all default, as are enabled addons. Looking into my environment variables from outside Blender, I also don't have any Qt related paths on my PATH environment variable. HOWEVER, when listing PATH from Blender's Python REPL, I see `C:\Users\olaf\AppData\Local\Temp\_MEI397042` which contains the PyQt5 files. There are over 130 of similarly named temp folders with PyQt5 stuff. I now suspect the [Blender Launcher](https://dotbow.github.io/Blender-Launcher/) is adding these folders and using PyQt5. Since I start Blender from it, the path is inherited from Blender. That much I confirmed. Starting from the executable directly, not from the launcher doesn't raise the errors.
> 
> Maybe this [issue](https://github.com/pyinstaller/pyinstaller/issues/6297) is related.
> 
> FYI: the version in the bl_info didn't get updated to 0.0.2, it still shows 0.0.1.

Oh awesome this is indeed it, the issue would fixed if Blender Launcher didn't modify its path, we could also modify path to make the addon work, hopefully we can find a better idea to not break things

**Comment by iyadahmed** [comment]
> can confirm blender launcher uses PyQt5, see code in here https://github.com/DotBow/Blender-Launcher/blob/v1.15.0-stable/source/windows/main_window.py.

Awesome, indeed they do use and modify path

**Comment by iyadahmed** [comment]
I just found this maybe this is the solution

https://doc.qt.io/qt-6/deployment-plugins.html#the-plugin-directory
https://doc.qt.io/qt-6/qcoreapplication.html#setLibraryPaths

**Comment by iyadahmed** [comment]
I've been trying to use `QCoreApplication.setLibraryPaths` without success, setting `os.environ["QT_PLUGIN_PATH"]` works though

**Comment by iyadahmed** [comment]
@OlafHaag 
I pushed a new release with `QCoreApplication.setLibraryPaths`, please let me know if it fixes it, I still cannot reproduce it here even with Blender Launcher

Commit: https://github.com/iyadahmed/blender_pyqt_example_addon/commit/ac692cf7b20d36fc7f234928d2195e433f2329ab

Release: https://github.com/iyadahmed/blender_pyqt_example_addon/releases/tag/v0.0.3
